project:
  type: website
  output-dir: docs

website:
  title: "surv-extrapolation"
  # navbar:
  #   left:
  #     - href: index.qmd
  #       text: Home
  #     - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Basics"
        contents:
          - index.qmd
          - basics-knitr.qmd
          - basics-jupyter.qmd
      - section: "Distributions"
        contents:
          - Exponential-distribution.qmd
          - Weibull-distribution.qmd
          - Gompertz-distribution.qmd
      - section: "Assessing the suitability of survival models"
        contents:
          - Visual-inspection.qmd
          - Log-cumulative-hazard-plot.qmd
          - AIC-BIC-tests.qmd
          - other-methods.qmd
      - section: "Methods"
        contents:
          - restricted-means.qmd
          - parametric-modelling.qmd
          - PH-modelling.qmd
          - external-data.qmd
          - other-hybrid-methods.qmd
  page-footer: "Copyright 2022, Nathan Green"
  repo-url: https://github.com/n8thangreen
  repo-actions: [edit, issue]

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto