project:
  type: website

website:
  title: "surv-extrapolation"
  # navbar:
  #   left:
  #     - href: index.qmd
  #       text: Home
  #     - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Basics"
        contents:
          - index.qmd
          - basics-knitr.qmd
          - basics-jupyter.qmd
      - section: "Layout"
        contents:
          - layout.qmd
          - layout-knitr.qmd
          - layout-jupyter.qmd
  page-footer: "Copyright 2022, Nathan Green"
  repo-url: https://github.com/n8thangreen
  repo-actions: [edit, issue]

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

