---
title: "Log Cumulative Hazard Plot"
---

`survival` package
from https://cran.r-project.org/web/packages/survival/vignettes/survival.pdf

```{r}
library(survival)

data("reliability", package = "survival")

vdata <- with(valveSeat, data.frame(id=id, time2=time, status=status))
first <- !duplicated(vdata$id)
vdata$time1 <- ifelse(first, 0, c(0, vdata$time[-nrow(vdata)]))
double <- which(vdata$time1 == vdata$time2)
vdata$time1[double] <- vdata$time1[double] -.01
vdata$time2[double-1] <- vdata$time1[double]
vdata[1:7, c("id", "time1", "time2", "status")]

vfit <- survfit(Surv(time1, time2, status) ~1, data=vdata, id=id)
plot(vfit, cumhaz=TRUE, xlab="Days", ylab="Cumulative hazard")
```


`flexsurv` package

```{r eval=FALSE}
Hexp(x, rate = 1, log = FALSE)
Hgamma(x, shape, rate = 1, log = FALSE)
Hlnorm(x, meanlog = 0, sdlog = 1, log = FALSE)
Hweibull(x, shape, scale = 1, log = FALSE)
```


```{r}
library("flexsurv")
fs1 <- flexsurvreg(Surv(recyrs, censrec) ~ group, data = bc, dist = "weibull")
plot(fs1, type = "cumhaz")
```


`muhaz` package

